# Generated by Django 3.1.2 on 2020-10-10 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_queue_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.branch'),
        ),
    ]
