# Generated by Django 3.1.2 on 2020-10-10 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201010_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.branch'),
        ),
    ]
