# Generated by Django 3.1.2 on 2020-10-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201010_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
